---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: webapp
  namespace: flux-system
spec:
  interval: 30s
  ref:
    semver: '>=4.0.0 <4.0.2'
  url: https://github.com/stefanprodan/podinfo

